version: 2

sources:
  - name: northwind
    description: Data from northwind ERP
    database: basic-buttress-436018-j2
    schema: erp_northwind
    tables:
      - name: Orders
        freshness: # make this a little more strict
          warn_after: {count: 5000, period: day}
          error_after: {count: 10000, period: day}
        loaded_at_field: cast(OrderDate as timestamp)

        description: '{{doc("order_docs")}}'
        columns:
          - name: OrderID
            description: Unique ID for this table
            tests:
              - unique
              - not_null
          - name: CustomerID
            tests:
              - relationships:
                  field: CustomerID
                  to: ref('stg_customers')
      - name: Customers
        columns:
          - name: CustomerID
            description: Unique ID for this table
            
      - name: OrderDetails
      - name: Categories
      - name: Products
      - name: Suppliers
